#include <iostream>
#include <string>
using namespace std;
int main() {
    string search;
    cout << "What do you want to search? :";
    cin >> search;
    if (search == "calculus"){
        cout << "Unang bagsak";
    }
    else if(search == "Comprog"){
        cout << "Pangalawang bagsak";
    }
    else if(search == "Econ"){
        cout << "Ang lala walang masagot bagsak nanaman";
    }
    else if(search == "Physics"){
        cout << "Last natong bagsak";
    }
    else if(search == "EXAM"){
        cout << "AYOKO NA BOSS!";    
    }
    else if(search == "Computer"){
        cout << "A MACHINE THAT CAN STORE AND PROCESS INFORMATION";
    }
    else if(search == "Programming"){
        cout << "IS THE MENTAL PROCESS OF THINGKING UP INSTRUCTIONS TO GIVE TO A MACHINE LIKE A COMPUTER";
    }
    else if(search == "Coding"){
        cout << "IS THE PROCESS OF TRANSFORMING THOSE IDEAS INTO A WRITTEN LANGUAGE THAT A COMPUTER CAN UNDERSTAND";
    }
    else if(search == "Abacus"){
        cout << "THE HISTORY OF COMPUTER BEGINS WITH THE BIRTH OF THE ABACUS";
    }
    else if(search == "Napier's Bones"){
        cout << "WAS A MANUALLY OPERATED CALCULATING DEVICE AND AS THE NAME INDICATES; IT WAS INVENTED BY JOHN NAPIER";
    }
    else if(search == "Pascaline"){
        cout << "ALSO CALLED ARITHMETIC MACHINE OR ADDING MACHINE";
    }
    else if(search == "Tabulating Machine"){
        cout << "WAS A MECHANICAL TABULATOR THAT WAS BASED ON PUNCH CARDS";
    }
    else if(search == "Differential Analyzer"){
        cout << "WAS THE FIRST ELECTRONIC COMPUTER INTRODUCED IN THE YEAR 1930";
    }
    else if(search == "Analytical Engine"){
        cout << "WAS A MECHANICAL COMPUTER THAT USED PUNCH CARDS AS INPUT";
    }
    else if(search == "Mark I"){
        cout << "WAS BUILT AS A PARTNERSHIP BETWEEN IBM AND HARVARD";
    }
    else if(search == "Digital Computer"){
        cout << "THESE ARE THE MODERN COMPUTERS WHICH ARE CAPABLE OF PROCESSING INFORMATION IN DISCRETE FORM";
    }
    else if(search == "Analog Computers"){
        cout << "USED TO PROCESS DATA GENERATED BY ONGOING PHYSICAL PROCESSES";
    }
    else if(search == "Hybrid Computers"){
        cout << "USED BOTH ANALOG AND DIGITAL TECHNOLOGY";
    }
    else if(search == "Mainframe Computers"){
        cout << "THESE ARE LARGE AND POWERFUL COMPUTERS THAT ARE USED BY LARGE ORGANIZATION";
    }
    else if(search == "Personal Computers"){
        cout << "ARE SMALL AND AFFORDABLE COMPUTERS THAT ARE DESIGNED FOR INDIVIDUAL USERS";
    }
    else if(search == "Mini Computers"){
        cout << "SMALLER AND LESS POWERFUL THAN MAINFRAME COMPUTER";
    }
    else if(search == "Workstation"){
        cout << "THESE ARE HIGH PERFORMANCE COMPUTERS THAT ARE USED BY PROFESSIONALS";
    }
    else if(search == "Embedded Systems"){
        cout << "ARE SPECIALIZED COMPUTERS THAT ARE BUILT INTO OTHER DEVICES";
    }
    else if(search == "Mobile Devices"){
        cout << "ARE SMALL AND PORTABLE COMPUTERS THAT ARE DESIGNED FOR ON-THE-GO USE";
    }
    else if(search == "RAM"){
        cout << "THESE ELECTRONIC DEVICE ARE FASTER IN SPEED";
    }
    else if(search == "HARD DISK"){
        cout << "ALSO CALLED HARD DISK DRIVE; ALSO AN ELECTRO-MECHANICAL DEVICE THAT HAVE LOWES SPEED";
    }
    else if(search == "System Software"){
        cout << "THOSE ARE SOFTWARE WITHOUT OUR PC OR LAPTOPS IT WON'T RUN";
    }
    else if(search == "Application Software"){
         cout << "WITHOUT EACH LAPTOP OR PC IT CAN RUN";
    }
    else if(search == "Hacker"){
          cout << "THEY WILL JUST WARN YOU SOMETHING ABOUT MALICIOUS ACTIVITY GOING AROUND";
    }
    else if(search == "Cracker"){
          cout << "THEY WILL TRY TO STEAL YOUR INFORMATION";
    }
     else {
        cout << "Invalid input";
    }
     
     return 0;
}
